name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:

jobs:
  iscan-job:
    runs-on: 8801302644/unify-iscan:latest
    name: Checkout repo
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'mediawiki'
      - name: Show results
        run: |
          ls -ltrh
          ls -ltrh mediawiki/
      - name: Scanning the mediawiki folder
        run: |
          ./main scan -p ./mediawiki --report-formats html -o ./results
