name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:

jobs:
  iscan-job:
    runs-on: ubuntu-latest
    name: Checkout repo
    steps:
      - uses: actions/checkout@v2
      - name: Show results
        run: |
          pwd
          ls -l
