name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reo pened, edited]
  push:
  
jobs:
   iscan-job:
      runs-on: ubuntu-latest
      steps:
        - name: CheckOut the Repo 
          uses: actions/checkout@v2
          with:
            path: 'scan_repo'
        - name: list before
          run: |
            ls -ltrh
            ls -ltrh scan_repo              
        - name: Pull iscan code
          uses:  sayeed89/unify-iscan-github-action@main
        - name: list after
          run: |
            ls -ltrh
            ls -ltrh scan_repo      
