name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reo pened, edited]
  push:
  
jobs:
   iscan-job:
      runs-on: ubuntu-latest
      steps:
        - name: CheckOut the Repo 
          uses: actions/checkout@v2
        - uses: sayeed89/unify-iscan-github-action@v1 
        - name: list after
          run: |
            ls -ltrh

          
        
      
