name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:

jobs:
  iscan-job:
      runs-on: ubuntu-latest
      container:    
        image: 8801302644/unify-iscan:latest
      steps:
      - name: super-step
        run: |
            ls -l
