name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reo pened, edited]
  push:
  
jobs:
   iscan-job:
      runs-on: ubuntu-latest
      steps:
        - name: Check Out Repo 
          uses: actions/checkout@v2
        - name: Building the docker image
          run: |
            docker build -t mediawiki-iscan:latest .
        - name: docker images list
          run: |
            docker images
