name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:

jobs:
  iscan-job:
    runs-on: ubuntu-latest
    name: Checkout repo
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'mediawiki'
      - name: Downloading iscan binary
        run: |
          wget https://raw.githubusercontent.com/sayeed89/terraform/main/main
      - name: Show results
        run: |
          ls -ltrh mediawiki/
          ls -ltrh iscan/
          pwd
          ls -l

