name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reo pened, edited]
  push:
  
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: list
        run: |
          pwd
          ls -ltrh
          env
      - name: Iscan Scan
        uses:  sayeed89/unify-iscan-github-action@main
