name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  push:

jobs:
  iscan-job:
      runs-on: ubuntu-latest
  new-job:
    runs-on: ubuntu-latest
    container:    
        image: 8801302644/unify-iscan:working
    steps:
      - name: super-step
        shell: sh
        run: |
            ls -l
