name: Scaning the code using iscan

on:
  pull_request:
    types: [opened, synchronize, reo pened, edited]
  push:
  
jobs:
   iscan-job:
      runs-on: ubuntu-latest
      env:
          DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
          ISCAN_PATH: ${{ secrets.ISCAN_PATH }}
      steps:
        - name: Check Out the Repo 
          uses: actions/checkout@v2
        - name: Building the docker image
          run: |
            docker build -t "$DOCKER_IMAGE":latest .
        - name: docker images list
          run: |
            docker images
        - name: running docker container
          run: |
            docker run -e ISCAN_PATH='$ISCAN_PATH' "$DOCKER_IMAGE":latest

